// DON'T EDIT *** generated by scaneo *** DON'T EDIT //

package db

import "database/sql"

func ScanMarker(r *sql.Row) (Marker, error) {
	var s Marker
	if err := r.Scan(
		&s.FrameIndex,
		&s.FrameImageIndex,
		&s.AccelerationX,
		&s.GPSLatitude,
		&s.GPSLongtitude,
		&s.MapLatitude,
		&s.MapLongtitude,
		&s.SpeedPerHourLowpass,
		&s.BrakeOnOff,
		&s.AcceleratorOnOff,
		&s.SteeringAngle,
		&s.AheadDistance,
		&s.AheadRelativitySpeed,
	); err != nil {
		return Marker{}, err
	}
	return s, nil
}

func ScanMarkers(rs *sql.Rows) ([]Marker, error) {
	structs := make([]Marker, 0, 16)
	var err error
	for rs.Next() {
		var s Marker
		if err = rs.Scan(
			&s.FrameIndex,
			&s.FrameImageIndex,
			&s.AccelerationX,
			&s.GPSLatitude,
			&s.GPSLongtitude,
			&s.MapLatitude,
			&s.MapLongtitude,
			&s.SpeedPerHourLowpass,
			&s.BrakeOnOff,
			&s.AcceleratorOnOff,
			&s.SteeringAngle,
			&s.AheadDistance,
			&s.AheadRelativitySpeed,
		); err != nil {
			return nil, err
		}
		structs = append(structs, s)
	}
	if err = rs.Err(); err != nil {
		return nil, err
	}
	return structs, nil
}

